# Generated by Django 3.0.3 on 2020-09-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200910_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='googleScholar',
            new_name='google_scholar',
        ),
    ]
