# Generated by Django 3.0.3 on 2020-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200910_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profiles_pics/default_profile_pic.png', null=True, upload_to='profiles_pics/'),
        ),
    ]
