# Generated by Django 3.0.3 on 2020-12-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200917_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(upload_to='articles/%Y/%m/%d'),
        ),
    ]
