# Generated by Django 3.0.3 on 2020-12-19 16:23

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201215_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rdf',
            field=models.FileField(blank=True, null=True, upload_to=article.models.Article._path_rdf),
        ),
    ]
